### ISSUE TITLE
get_platform_status() doesn't work

### ISSUE THREAD

**Issue by teaishealthy** [IreTheKID/valorant.py#6]
get_platform_status() doesn't work. I looked a bit into the code and I think you used `region=self.reigon` but I think you should have used `code=self.region`.
Although I'm not 100% sure.

**Comment by IreTheKID** [comment]
Can you please specify what error was raised or what `get_platform_status()` returned? I might've messed up the region string formatting.=P

**Comment by teaishealthy** [comment]
Here!
`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "\valorant\client.py", line 66, in get_platform_status
    url = _build_url(reigon=self.reigon, endpoint="status")
TypeError: _build_url() got an unexpected keyword argument 'reigon'`

**Comment by IreTheKID** [comment]
@teaishealthy It looks like I put in the wrong kwarg, but I've fixed it now. Thanks!
